# Мягкое введение в Python, часть 3

В [предыдущем блокноте](https://github.com/avidale/weirdMath/blob/master/python_tutorial_1.ipynb) мы познакомились с типами данных в Python, узнали про переменные, списки, циклы и условия. 

Во [втором блокноте](https://github.com/avidale/weirdMath/blob/master/python_tutorial_2.ipynb) мы обсудили функции, объекты и методы.

В этом блокноте мы поговорим про

## 4. Структуры данных

Подробнее и красочнее о структурах данных написано в [этом посте](https://vk.com/wall-130785301_92).

Напомним, что список (aka массив, aka list) - это просто последовательность значений через запятую, в квадратных скобках.

И это самая простая и популярная структура данных. Обращение происходит по номеру (начиная с 0). 

In [13]:
list_example = ['red', 'orange', 'yellow', 'green', 'blue', 'purple']
print('Длина списка: ', len(list_example))
print('Пятый элемент: ', list_example[4])

Длина списка:  6
Пятый элемент:  blue


Интересной альтернативой спискам являются <i>словари</i> - составные объекты, элементы которых можно доставать не по номеру, а по имени.

In [2]:
rus_en = {'дела':'business', 'как':'how'}
rus_en['привет'] = 'hello'
print(rus_en['привет'], rus_en['как'], rus_en['дела'])

hello how business


Примеры методов у словарей - keys() возвращает ключи, а values() - значения.

In [3]:
print(rus_en.keys())
# К сожалению, юникод - это одна из главных проблем Питона. Её можно решать, но проще избегать кириллицы :)
print(rus_en.values())
print(list(rus_en.keys()))
print(list(rus_en.keys())[0])

dict_keys(['дела', 'как', 'привет'])
dict_values(['business', 'how', 'hello'])
['дела', 'как', 'привет']
дела


<b>Задание:</b> создайте словарь salary, который для трёх сотрудников Alice, Bob и Charles содержит их зарплаты (50, 30 и 60).

In [ ]:
salary = """Salary"""
try:
    print(salary['Алиса'])
except TypeError:
    print('Словарь нужно записать на место текстовой переменной Salary!')

Мы начали изучать Питон, чтобы работать с данными.

Данные обычно хранятся в таблицах. А что такое таблица? Это набор столбцов одинаковой длины. Или набор строк одинаковой длины. В общем, говоря математически - это матрица.

<b>Задание:</b> Как бы вы, используя полученные знания, задали бы единичную матрицу размера 2x2?

In [ ]:
x =  # опишите здесь единичную матрицу.
print(x)

Вы всё правильно сделали! Теперь можно хотеть большего - например, чтобы наша матрица поддерживала математические действия, как и положено матрицам и векторам из линейной алгебры. Оказывается, объекты np.array умеют как раз это.

Тут я импортирую библиотеку ```numpy``` и даю ей короткое имя ```np```.

In [4]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)
print(A + B)
print(A * B)
print(np.dot(A,B)) # функция матричного произведения!

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


Массивы np.array индексируются через запятую - сначала строки, потом столбцы. Двоеточием обозначаются все элементы строки или столбца.

In [5]:
C = np.array([[i+j for i in range (10)] for j in range(10)])
print(C)
print(C[1,3]) # один элемент
print(C[:,3]) # весь столбец
print(C[9,:]) # вся строка
print(C[9,1:5]) # кусочек строки
print(C[2:4,1:5]) # кусочек матрицы из середины

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]
4
[ 3  4  5  6  7  8  9 10 11 12]
[ 9 10 11 12 13 14 15 16 17 18]
[10 11 12 13]
[[3 4 5 6]
 [4 5 6 7]]


**Задание**: 
1. Создайте объект np.array - вектор Y со значениями 4, 8, 9
2. Создайте объект np.array - матрицу X размера 3*2, с первым столбцом из единиц и вторым с последовательностью 1, 2, 3
3. Распечатайте вторую строку X, все строки X со второй до последней, первый столбец X
 

**Задание для гиков**: пользуясь функциями np.linalg.inv, np.transpose либо метод transpose, np.dot, рассчитайте вектор $(X^TX)^{-1}X^TY$


Ещё более сложной структурой данных является объект ```DataFrame``` из библиотеки ```pandas```. Если ```array``` - это усложнённый ```list```, то ```DataFrame``` - это усложнённый ```array```.

Подключим эту библиотеку:

In [6]:
import pandas as pd

В частности, ```DataFrame``` поддерживает именованные названия столбцов. 

Создадим массив с возрастом и доходом нескольких людей (заметьте, что я создал его из словаря).

In [7]:
data = pd.DataFrame({'age':[18, 35, 27, 24, 19]
    , 'income':[15000, 110000, 60000, 80000, 45000]})
print(data)

   age  income
0   18   15000
1   35  110000
2   27   60000
3   24   80000
4   19   45000


К таким таблицам можно обращаться по именам столбцов.

In [8]:
print(data['age'])

0    18
1    35
2    27
3    24
4    19
Name: age, dtype: int64


Кстати, список имён столбцов - это свойство columns объекта DataFrame

In [9]:
print(data.columns)

Index(['age', 'income'], dtype='object')


К любому столбцу дальше можно обращаться по номеру строк.

In [10]:
print(data['age'][1:3])

1    35
2    27
Name: age, dtype: int64


При желании таблицу можно сохранить на диск в формате csv, который поддерживается Excel и другими программами.

In [11]:
data.to_csv('data1.csv', sep = ';', index = False) 
# по умолчанию в качестве разделителя используется запятая, но здесь мы используем точку с запятой для совместимости с Excel. 

<b>Задание:</b> 
1. Создайте DataFrame XFrame из матрицы X (созданной в предыдущем задании). Напечатайте его.
2. Посмотрите, чему у XFrame равно свойство columns. Замените columns на список ['const', 'x1']. Снова напечатайте XFrame
3. Напечатайте первые два значения столбца 'x1'. 

А вот это способ отобразить таблицу чуть более красиво:

In [12]:
from IPython.display import display
display(data)

age  income
0   18   15000
1   35  110000
2   27   60000
3   24   80000
4   19   45000

Напомним, что подробнее и красочнее о структурах данных написано в [этом посте](https://vk.com/wall-130785301_92).

И вообще, подписывайтесь на [vk.com/mat.chast](https://vk.com/mat.chast), тут будет много интересного дальше :)